// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CurrentUser struct {
	User   *User  `json:"user"`
	APIKey string `json:"apiKey"`
}

type Follow struct {
	FollowingSince string `json:"followingSince"`
	User           *User  `json:"user"`
}

type Mutation struct {
}

type Post struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	User      *User  `json:"user"`
	Text      string `json:"text"`
}

type Query struct {
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
	Following []*Follow `json:"following"`
	Followers []*Follow `json:"followers"`
	Posts     []*Post   `json:"posts"`
}
