// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: version.sql

package database

import (
	"context"
)

const getVersion = `-- name: GetVersion :one
SELECT version()
`

func (q *Queries) GetVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
